companies:
  - stripe
  - cohere
  - confluent
  - openai
  - snowflake
  - acorns
  - homebase
  - sentry
  - decagon
  - figma
  - base
  - ramp
  - faire
  - notion
  - brex
  - gusto
  - rubrik
  - doordashusa
  - doordashcanada
  - instacart
  - robinhood
  - chime
  - coinbase
  - affirm
  - databricks
  - asana
  - calendly
  - lever
  - PaloAltoNetworks2
  - sandisk
  - wix2
  - boschgroup
  - westerndigital
  - aecom2
  - aristanetworks
  - qualtrics
  - benchling
  - chewy
  - epicgames
  - pinterest
  - spotify
  - zoom
  - dropbox
  - box
  - adobe
  - autodesk
  - palantir
  - visa
  - linkedin
  - anthropic
  - cloudflare
  - datadog
  - okta
  - handshake
  - docusign
  - charliehealth
  - perplexity
  - stabilityai
  - deepmind
  - adidas
  - uber
  - lyft
  - airbnb
  - spotify
  - immuta
  - voodoo
  - whoop
  - veeva
  - allegiant
  - nimblerx
  - metabase
  - pwc
  - mcdonalds
  - ucla
  - blueorigin
  - baseten
  - crunchyroll
  - jetblue
  - replit
  - unity
  - snap
  - google
  - gitlab
  - github
  - microsoft
  - apple
  - netflix
  - amazon
  - meta
  - sanofi
  - jpmorgan
  - goldmansachs
  - bankofamerica
  - dell
  - hp
  - intel
  - nvidia
  - qualcomm
  - salesforce
  - sap
  - qfg
  - siemens
  - generalmotors
  - ford
  - boeing
  - lockheedmartin
  - raytheon
  - northropgrumman
  - sobeys
  - loblaws
  - walmart
  - target
  - costco
  - kroger
  - ceridian
  - workday
  - adp
  - ultimatehr
  - paycom
  - intuit
  - fedex
  - ups
  - dhl
  - citibank
  - americanexpress
  - mastercard
  - paypal
  - johnsonandjohnson
  - pfizer
  - merck
  - abbvie
  - roche
  - novartis
  - bayer
  - astrazeneca

filters:
  title_keywords:
    - software engineer
    - developer
    - backend
    - frontend
    - fullstack
    - full stack
    - swe
    - software developer
    - web developer
    - application developer
    - systems engineer
    - systems developer
    - mobile developer
    - mobile engineer
    - programmer
    - biotech
    - bioinformatics
    - product manager
    - associate product manager

  exclude_keywords:
    - intern
    - internship
    - extern
    - externship
    - co-op
    - senior
    - sr.
    - staff
    - lead
    - director
    - principal

  allowed_countries:
    - USA
    - US
    - United States
    - United States of America
    - Canada
    - CA

  hours: 24
